### PR TITLE
Handle 'partial' pseudo-modifier in the Modifiers production.

### PR DESCRIPTION
**Pull request by vsajip**

### CODE REVIEW

**Comment by revusky** [comment]
To tell the truth, I'm not sure it's a good idea to have the `Modifiers` production take a boolean parameter (to indicate whether `partial` is permitted in this spot. The general problem with productions taking parameters is that it only works at the parsing stage, not in a lookahead. Or more precisely, if `Modifiers` takes a boolean parameter, the tool generates two methods: `Modifiers(boolean partial)`and `check$Modifiers()` 

I mean, any of check\$XXX methods generated have no parameters, so the `partial` arg passed in is only accessible when parsing, but not in a lookahead. In general, by the way, this is something of a problem with parameters passed into a parser production. The generated lookahead routines don't receive these parameters. 

This also is why we have the instance variable `permissibleModifiers` rather than passing it in as a parameter (which would look more natural) because something passed in as a parameter is not visible in a lookahead, only in parsing. 

So the upshot is that, even though it might look more awkward, it might be better to have `partial` be an instance variable, just like `permissibleModifiers` is. And then `Modifiers` would remain no-args.

The other possibly tricky aspect of "partial" is that it is a  *soft* keyword. If the keyword "partial" is not permitted in that spot, then I guess it should be scanned as an identifier. But I think you're quite aware of that issue...

**Comment by vsajip** [comment]
OK, fair enough. I did think about the not-available-in-lookahead part, but I just thought I'd implement it and get your feedback. Of course one problem with using instance variables is that the code might not be re-entrant / thread-safe, but perhaps that's a peripheral concern. Shall I close this PR, then?

**Comment by revusky** [comment]
Well, I'm not so absolutely sure what is best. But, truth told, I don't know offhand if there is any very strong reason to handle "partial" in the Modifiers production. I mean, "partial" is not really a modifier in the same way "private" or "static" is. So, arguably, the way it was before might actually make more sense.

But I wouldn't worry too much about thread safety. I think the assumption is that any parser instance is definitely single-threaded. If we do need to parse input in another thread, we're just instantiating another XXXParser (and XXXLexer) instance.

**Comment by vsajip** [comment]
No, I think you're right. There's no need to do this.

**Pull request closed without merging**
