### PR TITLE
Add support for polyglot generation for the C# grammar.

### PR DESCRIPTION
**Pull request by vsajip**
Please leave this for me to merge.

### CODE REVIEW

**Review by revusky — APPROVED** [review]

**Comment by vsajip** [comment]
Oh no! I assigned myself to this and asked for it to be left for me to merge! Please don't work on stuff I've assigned to me.

**Comment by zhicwu** [comment]
> Oh no! I assigned myself to this and asked for it to be left for me to merge! Please don't work on stuff I've assigned to me.

You can [convert a pull request to a draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) :D

**Comment by vsajip** [comment]
True enough. Though as there are only two of us actively working on the project, I'd have hoped to avoid having to resort to that ...

**Comment by revusky** [comment]
> Please leave this for me to merge.

Oops, I guess I just got excited and clicked on merge without reading the above. Well, I guess the message was too long! :-)

**Pull request merged**
