### PR TITLE
Make minor changes to facilitate Python code generation.

### PR DESCRIPTION
**Pull request by vsajip**
These changes are to avoid having circular import issues in generated Python code.

### CODE REVIEW

**Review by revusky — APPROVED** [review]
I guess this is fine. It involves having a separate wrapper called LiteralExpression, which I had thought unnecessary, but if this facilitates your Python work, then... I mean, from my POV, it doesn't really matter that much. By the way, AFAICS:

     LiteralExpression : Literal #LiteralExpression ;

is the exact same as:

     LiteralExpression# : Literal ;

The AST it builds is the same but the code is a bit more terse since you avoid avoid repeating the production name that way. OTOH, another question is why have two separate productions, LiteralExpression and Literal in this case.  You could, AFAICS, just write:

     LiteralExpression# : 
        <INTEGER_LITERAL>
        |<LONG_LITERAL>
        |<FLOATING_POINT_LITERAL>
        |<CHARACTER_LITERAL>
        |<STRING_LITERAL>
        |<TEXT_BLOCK_LITERAL>
        |"true"|"false"|"null"
      ;

And then you don't need a separate `Literal` production (since that is not used anywhere else, it seems.) However, none of it matters very much. I guess I just point out the above just to help you gain a mastery of this stuff. I am approving the PR, of course.

**Comment by vsajip** [comment]
Thanks very much, I take all your points on board. I'm still getting used to all the new terse goodness available :smile: we can put the improvements you suggest in at any point. I wanted to minimize the changes to make the review quicker / easier.

**Comment by vsajip** [comment]
On reflection, I would say
```
LiteralExpression# : Literal ;
```
is worth keeping - for cases where you're working at the lexer level it seems reasonable to have a top-level for literals, whereas `LiteralExpression` is there to provide expression-level APIs such as `isAssignableTo()`, etc.

**Comment by revusky** [comment]
Well, as a practical question, I think that if it results in the same tree, it doesn't matter very much.

**Pull request merged**
