### PR TITLE
Provide JUnit Tests for Node API.

### PR DESCRIPTION
**Pull request by angelozerr**
Provide JUnit Tests for Node API.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR provides JUnit for Node API (getFirstChild, getLastChild, findNodeAt, etc). Those tests help me to fix somes bugs (see changes of ftl templates).

I set JUnit tests in the `src/test/java` folder (maven layout). Today we have `src/java`, it should be better to rename to `src/main/java` to follow the (future) maven layout.

Please note, this PR update the `.classpath` file of Eclipse (to add JUnit in the classpath) but it's a bad idea to commit in github project those settings files, but let's keep like this. When we will move to maven (or gradle), we will able to remove it.

To run test with Eclipse IDE, just open the JavaCCParserTest class and do Run as JUnit Tests.

This test uses JSON grammar but not from the examples folder (as a string), because we are sure that tests will continue to work even if JSON.javacc file will change.

**Comment by revusky** [comment]
Regarding src/main/java, I guess I'll do it. Why not? I was wondering what your opinion on package names was. I was considering changing javacc.* to com.javacc.* since I do own the javacc.com domain. Do you think that is a good idea or it doesn't matter?

**Comment by angelozerr** [comment]
I see more and more new projets which are using Io. Io is for new and cool project (microprofile Io, quarkus Io, etc) so what about using io.javacc? I think it Can beba good Idea because using Io is for cool and New projets which is exactly your goal

**Comment by revusky** [comment]
Well, I don't know. I just looked at this and .io domains are more expensive. If I purchase javacc.io from Godaddy (it is available) it costs 49 euros. https://es.godaddy.com/domainsearch/find?isc=NPEUR19ES&checkAvail=1&tmskey=&domainToCheck=javacc.io while javacc.fr, for example, is only 8 euros. Why are people willing to pay more for a .io domain? (Maybe it is more cool...)

But, really, I'm hardly convinced that people registered .io because it is really considered so desirable. It may just be that the .org and .com domains were already taken, so they went with .io. My own tendency is to think that .com is really the go-to domain, in general, but .org is more like the typical domain for an open source project. Of course, javacc.org is taken. 

But since I already own javacc.com I don't really see much point in paying 49 euros for javacc.io. Of course, I could rename the packages to io.javacc.* without even owning the domain, but really, then, if one doesn't even own the domain, I would just stick to javacc.* since it is simpler. 

Well, for now, I think I won't do anything. You may have noticed that I moved everything under src/main as per recommended Maven layout. It was easier just to do that than to talk about it.

**Comment by angelozerr** [comment]
Me i love io.javacc because it follows the same npattern than other super cool project, but it's your project, do as you wish  By using Io you could rename javacc21 to javacc.io which could mean: its the New generation of javacc. More i find Io is adapted for javacc. In input you set a grammar, in output you generate a parser. 

You could use Io for freemarker io.freemarker will mean New generation of freemarker

**Pull request merged**
