### PR TITLE
Added C_CONTINUATION_LINE flag

### PR DESCRIPTION
**Pull request by Gravelbones**
This is adding a new flag C_CONTINUATION_LINE which will add handling of <backslash> <newline>, corresponding with C/C++ preprocessor.
To have proper line numbering, the creation of line offset index is done during the processing of the input, rather than after.
For some reason my commit changes a bunch of linefeed endings.

### CODE REVIEW

**Comment by revusky** [comment]
You know, looking through this, I think I'll have to reject the patch -- but to be clear, not because I (a) don't see the need to solve this OR (b) because I'm not going to help you resolve the issue. The problem is that the approach you've taken, of patching the `mungeContent` method does not really seem desirable to me. The whole thing will eventually get rather unwieldy. What I think is needed to deal with this sort of thing is something analogous to, say, the TOKEN_HOOK mechanism. If you define (i.e. INJECT) a method in the XXXLexer class of a certain name, it should be called at the end of this pre-lexical phase. I think it could be called PRE_LEXICAL_HOOK or something like that. I believe that a PRE_LEXICAL_HOOK like this might do the trick:

    private void PRE_LEXICAL_HOOK() {
        boolean inPreprocessor = false, atLineStart = true;
        //The index of the last backslash we encountered, -1 if undefined.
        // This is only set if we are within a preprocessor directive.
        int lastBackslashIndex = -1;
        int index = 0;
        while (index < content.length()) {
            char ch = content.charAt(index++);
            if (ch == '#' && !inPreprocessor && atLineStart) {
                inPreprocessor = true;
                atLineStart = false;
            }
            else if (ch == '\n') {
                if (!inPreprocessor) atLineStart = true;
                else {
                    if (lastBackslashIndex != -1) {
                      // If we have the lastBackslashIndex set
                      // we set the buffer offsets from there 
                      // up to (and including) this newline to IGNORED
                        for (int i=lastBackslashIndex; i< index; i++) {
                          tokenLocationTable[i] = IGNORED;
                        }
                        lastBackslashIndex = -1;
                    }  else {
                        inPreprocessor = false;
                        atLineStart = true; 
                    }
                }
            }
            else if (ch == '\\' && inPreprocessor) {
              lastBackslashIndex = index -1;
            }
            else if (!Character.isWhitespace(ch)) {
              atLineStart = false;
              lastBackslashIndex = -1;
              atLineStart = false;
            }
        }
    }

As best I can see, what you need is that if you have a line like:

   #define ..... \(Newline)
   ... the rest of the line

We need the backslash and the newline in the first line to be ignored. (And any whitespace in between if there is any.)

So please let me know if the above proposal works for you. I would say in closing that I was pretty positively impressed with the intellectual effort you made to figure out the code and add a setting and all that. I don't actually reject absolutely the extra C_CONTINUATION_LINE setting, though I do wonder whether it is relatively special interest. Well, I dunno, I'm thinking about that. Maybe there is enough interest in this to add it. It doesn't really cost anything. It's just a question of having the method above in the template and invoking it at the end of the constructor, based on whether the setting is on. SO, something like:

     [#if C_CONTINUATION_LINE]
        handleCPreprocessorContinuationLInes();
    [/#if]

A notable aspect of this is that if the method is private, if the setting is unset, then the method doesn't even get generated finally, because of the DeadCodeEliminator logic. So it effectively doesn't cost anything....

**Comment by Gravelbones** [comment]
My main concern is that the linenumbering is correct when parser "sees" it, e.g. any skipped linefeed gets "counted".
And that when doing getImage(), I do not get these skipped characters.
My solution did have the benefit of fixing lineoffsets with both '\r' and '\n' lines. :)
So as far as I can understand this code, I will get the skipped characters when doing getImage() and that is a no go.

**Comment by revusky** [comment]
> My main concern is that the linenumbering is correct when parser "sees" it, e.g. any skipped linefeed gets "counted".

Yes, that is what I thought you wanted and what I propose does that. The calculation of line numbers of any location does not skip any characters! Here is a key point to look at: 

https://github.com/javacc21/javacc21/blob/master/src/ftl/java/Lexer.java.ftl#L581

This is the method used to get the "image" of a token and it skips the IGNORED locations, but again, the line number info will be fine. If you look at the routines that deal with the line numbers, they make no referenced to any IGNORED locations.

> And that when doing getImage(), I do not get these skipped characters.

Yes, see above. Also see: https://github.com/javacc21/javacc21/blob/master/src/ftl/java/Lexer.java.ftl#L513-L515

The core tokenization routine will skip those characters, which is what you want, but the line calculation logic, calculating what line number corresponds to what offset, that is not affected by this. This is how it works by design. I myself am very very obsessed with giving the user accurate location info.

> My solution did have the benefit of fixing lineoffsets with both '\r' and '\n' lines. :)

Oh, you mean a line that ends in a lone '\r'? Well, that might be a good idea, but really the only two cases in practice nowadays are "\r\n" and "\n". I think the Mac OS before it became basically a BSD Unix variant did use a lone "\r". 

But anyway, that's pretty much orthogonal to this issue of the C preprocessor continuation line.

> So as far as I can understand this code, I will get the skipped characters when doing getImage() and that is a no go.

No, I think you're misreading the code. :-) Well, just try it, I guess.

**Comment by revusky** [comment]
Actually, I just implemented it as described above. If you set the new setting `CPP_CONTINUATION_LINES=true` it marks the relevant locations as IGNORED. In particular see: https://github.com/javacc21/javacc21/blob/master/src/ftl/java/Lexer.java.ftl#L195-L197

**Comment by Gravelbones** [comment]
If I replace the code with something else, it works as intended. :)
As I have tried to explain, the replacement is all over regardless of anything.
Even inside string literals this replacement have to take place and priority.
So here is my code. I still have too many problems with lineendings fixes, to do a clean pull request.
[fixup.txt](https://github.com/javacc21/javacc21/files/7934484/fixup.txt)

**Comment by revusky** [comment]
Well, I guess I misunderstood what you needed. I was under the impression that the continuation line only applied to lines that were part of the C preprocessor and I thought that meant it only applied in lines that start (leaving aside initial whitespace) with a # character. That was the meaning of the method that I put in there. Your method is actually simpler, about half as long, because it just applies to all lines, whether they start with # or not. In any case, you see that the approach works. You just mark the \[EOL] as locations to be skipped, right?

Finally, it may be that the better approach is just to have this PRE_LEXICAL_HOOK defined and then you can inject that into your XXXLexer class and it will be called in that spot, at the end of the constructor. And then anybody with whatever special need (at least assuming it can be addressed this way) can just define their own PRE_LEXICAL_HOOK method.

What do you think of that as a general solution?

**Comment by Gravelbones** [comment]
I think that would be a good solution.
Could also solve the question about when to do "global" initialization of the lexer class.
So that might be sort of suggestion to do a PRE_PARSER_HOOK as well. :)

**Comment by revusky** [comment]
Finally, I decided to leave it as a setting. It's C_CONTINUATION_LINE. 

Sorry to be a bit slow on such a trivial thing, but I've been rather absorbed with some other things. I have a working C# parser (up to 6.x and most of 7.x, not sure). See https://github.com/javacc21/javacc21/blob/master/examples/csharp/CSharp.javacc

Oh, another preprocessor-related thing is the whole issue of comments. In working on the C# grammar, it came to my attention that my approach to the preprocessor was wrong (a bit, anyway). The way I implemented it, the preprocessor is totally orthogonal to the C# grammar (both lexical and syntactic) so it just runs over the source and marks the lines as active or inactive. However, I now see, from running over the various C# (mono, really) source code, that it is possible to comment out pre-processing directives. So you can write:

       /*
           \#if foo
           ...
          \#endif
     */

to comment out the code inside the comment *including* any pre-processor directives. I had previous believed that to comment out any nested pre-rpocessor directives, you would have to use \#if false...\#endif since the preprocessor directives are processed *before* even lexical processing. 

WRONG. 

The preprocessor (in C/C++/CSharp) is comment-aware. The other thing I realize is that in CSharp it also has to be string literal awarey. Well, multiline string literals. You could conceivably have:

      string s = @"
          multiline string literal
          \#if foo
      "

And for complete correctness, it has to be aware of that! So I have to redo it somewhat! Well, there aren't multiline string literals in C that I know of, so the only issue is multiline comments. I find this whole thing kind of annoying because it means you can't exactly re-use the pre-processor for any other DSL as-is, because your DSL has to have the same commenting style. But not to worry. I'll have all this worked out at some point quite soon.

**Comment by revusky** [comment]
> Haven't been active myself, so no problem. I worry a bit about using trim to detect whether or not it is a true continuation line. Pretty sure that it only removes spaces and not tabs or formfeed which are acceptable characters too. 

Well, actually, I just checked and trim() removes any character 0x20 (space) or below. So it removes tab and form-feed and a host of junky control characters that should never even be there AFAICS. So, I think it is okay. I was just playing around with writing the method as tersely as possible. What is it now? 7 lines? But aside from that, since you're the only person (at least for now) using the feature, if you want to replace this method with something else, I don't really care either. But I think this is okay.

Actually, you know, another concern might be whether the thing is fully unicode-aware (it's not) as there are some various unicode characters that count as whitespace. Beyond 0xFF (and even beyond 0xFFFF, i.e. extended unicode there might be.) But finally, I don''t think its much of a real issue in this instance.

>So the new implementation will not catch those cases. I see some problems with expanding tabs in mungeContent. In most cases you can't make a global standard value for this, because each use case may require a different value.

I've been wondering what to do about this. I implemented TABS_TO_SPACES initially to support Python (or Python-ish languages) simply because that's the most bloody-minded way of dealing with the whole problem. 

Then I just decided (and it's quite recent to make that the default (though maybe I'm getting cold feet on that.) A related issue is PRESERVE_LINE_ENDINGS=false as a default, so that it just converts all the CRLF to LF internally. *By default*....

The thing about this is that it is configurable, but the issue with something being the default is that, as a practical matter, that's what 99% of people will end up using.

The PRESERVE_LINE_ENDINGS thing looks to be less controversial because, for one thing, it's hard to imagine very many use cases where anybody would care about it. But you're quite right that what makes the tabs issue more of a problem is that there is no clear answer to how many spaces a tab character represents. The main problem with leaving TAB characters alone is that you have this problem in terms of reporting column positions in error messages. And that still has the problem of there being no clear standard, 4 space offsets, 8 spaces, etc. The problem with converting tabs to spaces (aside from the issue of how many spaces, which is always an issue anyway) is that the absolute offsets in the file change. So, when you expand tabs, offset 1037 in the file becomes 1108 or something in the internal buffer. However, I think it's a cinch bet that most people relate to line/column a lot more than absolute offset! So, usually, it's more important for those to make sense.

There is certainly a case for just respecting absolutely the original input by default, and then putting in these options to convert the newlines or spaces. But there is also a case for converting them by default internally because the default is what most people will use in practice, and overall, it probably makes life simpler. Usually it does...

> E.g. if it gets included into a editor where the user can select the indentation. So for my use I will go with no expansion of tabs.

Well, that's an option, you just set TABS_TO_SPACES=0 and it leaves them alone. The problem there is that there is no special disposition when it comes to location reporting. So, a location preceded with 3 tabs counts as column 4, not column 13 or 25 (assuming 4 or 8 spaces respectively).

**Comment by Gravelbones** [comment]
Cool, about trim taking everything. I can live with that.
For now I don't care about other unicode spaces, as I doubt most compilers even support those.
For handling tabs, the "correct" place would be in getCodePointColumnFromOffset (Lexer.java.ftl), either by changing numSupplementaryCharactersInRange to do it while checking for surrogates or do it in another function (which need to handle surrogates anyway).
But for now I don't really need correct column position, and it will only be correct if tab is set to whatever value I choose.

**Comment by revusky** [comment]
Hi, sorry again to be slow in getting back to you. I was just really absorbed in what I was doing. In the last couple of days, I completed [a grammar for C#](https://github.com/javacc21/javacc21/blob/master/examples/csharp/CSharp.javacc). It took me just about 4 weeks to write. But this one now generates a parser that can run over an entire test suite I put together of over 50,000 source files, parses every one, including ones that have tricky uses of new language features in C# 9 and 10. 

As for the whole tabs thing, I finally redid it. The way it works now is that, by default, if you don't specify any setting, it just leaves the tabs alone and reports any error locations as if a tab is one horizontal offset. If you set, say, TAB_SIZE=4, it converts the tabs to spaces on that basis, and you get sane location reporting. And if you set TAB_SIZE=n and you say PRESERVE_TABS=true, then it leaves the tab characters be, but it reports columns based on the idea that tabs are whatever size were specified. Finally, I just implemented it by adding an extra bitset to keep track of which lines need adjustment. If a line contains any literal tab characters OR extended unicode, i.e. >0xFFFF code points, then that bitset is set for that line, and it runs over the text and makes the adjustment when it has to report the location. And if it's not set, like everything on a line is a 16-bit code unit, it just uses the simple logic.

In other matters, I've basically decided (or we've decided, since I think that Vinay is quite on board with this) to move away from the "JavaCC" product naming. And the Number 1 candidate for a replacement name is Congo, i.e. CongoCC or Congo Compiler Compiler. I registered the domain name congocc.org recently. And, since I've had nothing but problems with that Discourse App I installed at parsers.org, I decided to put up an alternative that looks promising. So, maybe you could sign up there at https://discuss.congocc.org/ and raise some issue or say something. So if you have any more to say about this whole topic here or anything else, please write your comment there. Meanwhile, I'm going to close this particular issue, since I think it is dealt with.

**Pull request closed without merging**
