### PR TITLE
Remove items which look unnecessary, and mark areas which could be co…

### PR DESCRIPTION
**Pull request by vsajip**
…nditionally generated in future.

### CODE REVIEW

**Comment by revusky** [comment]
To be bluntly honest, I just don't see what problem any of this really addresses. The DeadCodeEliminator approach really does work pretty well. If some method or field is not used, we just remove it. It's not even particularly computationally expensive, it seems. And we have a [second pass](https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/FilesGenerator.java#L260-L265) anyway, to pretty-print the source, add some getter/setters, and things like this. I mean, if we really are generating dead code, then we should go to the source of the problem, which is that DeadCodeEliminator.java is not working properly. But actually, I think it is, so....

**Comment by vsajip** [comment]
What about the parsers generated in other languages? How would dead code be eliminated in them?

**Comment by vsajip** [comment]
Also, it looks like the methods I commented out are not used anywhere in the code anyway - perhaps they are a holdover from earlier versions.

**Comment by revusky** [comment]
> What about the parsers generated in other languages? How would dead code be eliminated in them?

Well, I guess the same way. DeadCodeEliminator.java is less than 100 lines of code. The same method for C# would not be very different in size. As for Python, well, I suppose there aren't really private fields and methods officially, but there are naming conventions, no? Also some sort of annotation, I think. Again, the thing about this is that it stresses the system, that we're using internally the machinery we created for general use.

Of course, there are things that really are just never used, and should just be deleted when it comes to our attention, but there are plenty of things that are used sometimes but not always. For example, if you have a completely LL(1) grammar, then even things like `currentLookaheadToken` and `scanToken`, I suppose they're never referenced and should be identified as dead code and simply are not generated. (Not 100% sure actually, would have to check...)

Of course, the other question is whether Python or CSharp have a "code too large" issue. If not, then dead code elimination is harldy that urgent. So we generate a bunch of unused code. If it's not even causing a problem... I mean, okay, eventually, just to have an extra polished tool, we'd want to not generate the dead code, but it might not even be much of a practical problem anyway.

**Pull request closed without merging**
