### PR TITLE
Small fixes (; & param assignment)

### PR DESCRIPTION
**Pull request by MarcMazas**
Some small fixes in templates for avoiding compiler warnings

### CODE REVIEW

**Review by revusky — APPROVED** [review]
The second file is a superfluous semicolon. As for the truncateCharBuff change, I am not certain where the improvement lies. The parameter `amount` is already being passed by copy, since it is a primitive. Why the need to create another copy, `am`, which is just a copy of a copy? To tell the truth, I'm approving the PR because finally, I don't want to discourage you (or anybody) from learning the code.

**Comment by MarcMazas** [comment]
<The parameter amount is already being passed by copy, since it is a primitive. Why the need to create another copy, am, which is just a copy of a copy?/>
What the compiler really does is not obvious (it uses registers, JIT optimizes, ...) (especially if you take the good habit to declare the parameters and methods final). Why compiler people would still generate such a warning for primitive types if it would really be useless? This would have been something well known, 25 years after java's birth, wouldn't it?

**Comment by revusky** [comment]
> What the compiler really does is not obvious (it uses registers, JIT optimizes, ...)

I grant that I am not so specialized in such questions, but I am really pretty sure that defining the extra local variable there does not help the compiler in any way. As best I can see, the warning about modifying a parameter passed in is just *stylistic* advice, based on the idea (probably false in this case) that code that modifies a parameter is less clear. Something like that. That could be true in general, but I think it's a rather dubious concept in such a short method. On my last run at using IntelliJ, it would emit an astounding number of warnings about things that I was pretty sure were not a real issue and I turned most of them off in settings. You might consider doing the same.

Consider this: if your IDE did not emit a warning about this code, would you have thought, on your own, that there was any problem with it?

**Comment by MarcMazas** [comment]
<On my last run at using IntelliJ, it would emit an astounding number of warnings about things that I was pretty sure were not a real issue and I turned most of them off in settings. You might consider doing the same./>
I work in Eclipse. On most of my (personal & corporate) projects I turn ON all warnings and I FIX them (and ask my team to do the same) (and this is not time consuming), so I (we) do not leave any potential problems, I also configure the formatter, the save actions..., ask the team to use the same, so the code follows the same standards whoverer works on it.
With JavaCC I have to change some severity levels to get rid of warnings in generated code, but one on my goal (for JavaCC & JavaCC21 is to fix them).
So for JavaCC21 I would like to have common settings (i.e. checked-in/out) for compiler, formatter & save actions.

**Comment by revusky** [comment]
> I work in Eclipse. On most of my (personal & corporate) projects I turn ON all warnings and I FIX them (and ask my team to do the same) (and this is not time consuming), so I (we) do not leave any potential problems, I also configure the formatter, the save actions..., ask the team to use the same, so the code follows the same standards whoverer works on it.

It is not very relevant whether we are talking about Eclipse or Intellij or something else, the principle is the same.

What you are saying makes some sense, but really, only based on two assumptions:

- The warnings really are indicating *potential problems.* 
- The code in question is code that you (and your team) is maintaining by hand.

In terms of the first point, it really does seem that a significant percentage of the warnings that these tools report (in particular, if you activate ALL warning categories) are simply spurious. 

As for the second point, which is more fundamental, all of this really goes out the window if we're talking about *generated code*. The whole idea of being so concerned about whether the code that a tool *generates* does not generate these various warnings is.... well, I don't really know how to put it diplomatically... as far as I can see, this is a concept that is most generously described as *silly*.

Very typically, the code that tools like this *generate* looks nothing like the code that people would write by hand, so to give bug reports based on *generated code* causing warnings.... 

Now, that said, I try my best for the code generated by the tool to even be pretty good. (Though, of course, it varies...) How do you think the code generated by JavaCC21 looks in comparison to what is generated by the legacy tool?

But the other overarching issue here is that I really have a lot on my plate. So many things I want to do. I really think you should understand my position and be very hesitant about raising *ersatz issues*, like the *generated code* causing warnings. 

To be clear, issue #53 is (or was) a real bug and I am glad you reported that. But reporting that the tool generates code that causes warnings in Eclipse.... I mean, the obvious solution (and I assume one can do this) is just to turn off the warnings for the part of the source tree that is *generated*.

**Comment by MarcMazas** [comment]
<I mean, the obvious solution (and I assume one can do this) is just to turn off the warnings for the part of the source tree that is generated./>
Well, the only way to turn OFF warnings for part - not all - of a project is to add @suppressWarnings(...) annotations on the classes ; so we could add them in the templates where needed.

**Comment by MarcMazas** [comment]
Well, I see that you have reverted the 'parameter should not be assigned'.
A small test shows that one cannot rely only on assuming things or looking at byte code. The JIT compiler can do many things on the byte code.

Results of the test (see code to figure out what the numbers are):
results for public: 4896	4916	4928	2426	2409	
results for protected: 5657	2811	5694	2826	2819	
results for package: 5988	3013	5963	3028	3005	
results for private: 5421	2743	5412	2735	2747	
total = 2000

Class:
package mma;

@SuppressWarnings({
    "static-method", "unused", "javadoc"
})
public class PerfTest {
  
  private static final long NBCALLS = 100000000;
  private static final long NBLOOPS = 100;
  private static long total = 0;
  
  public PerfTest() {
    //
  }
  
  public static void main(String[] aArgs) {
    
    PerfTest pt = new PerfTest();
    
    run_public(pt);
    run_protected(pt);
    run_package(pt);
    run_private(pt);
    
    System.out.println("total = " + total);
  }

  private static void run_public(PerfTest pt) {
    
    long et;
    long bt;
    long tp;
    long ctr;
    long[] tpa = new long[5];
    
    for (int k = 0; k < NBLOOPS; k++) {
      int l = 0;
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mu(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mun(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.muf(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mu_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.muf_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
    }
    System.out.print("results for public: ");
    for (int m = 0; m < 5; m++) {
      System.out.print(tpa[m] + "\t");
    }
    System.out.println();
  }

  private static void run_protected(PerfTest pt) {
    
    long et;
    long bt;
    long tp;
    long ctr;
    long[] tpa = new long[5];
    
    for (int k = 0; k < NBLOOPS; k++) {
      int l = 0;
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mo(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mon(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mof(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mo_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mof_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
    }
    System.out.print("results for protected: ");
    for (int m = 0; m < 5; m++) {
      System.out.print(tpa[m] + "\t");
    }
    System.out.println();
  }

  private static void run_package(PerfTest pt) {
    
    long et;
    long bt;
    long tp;
    long ctr;
    long[] tpa = new long[5];
    
    for (int k = 0; k < NBLOOPS; k++) {
      int l = 0;
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mp(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mpn(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mpf(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mp_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mpf_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
    }
    System.out.print("results for package: ");
    for (int m = 0; m < 5; m++) {
      System.out.print(tpa[m] + "\t");
    }
    System.out.println();
  }

  private static void run_private(PerfTest pt) {
    
    long et;
    long bt;
    long tp;
    long ctr;
    long[] tpa = new long[5];
    
    for (int k = 0; k < NBLOOPS; k++) {
      int l = 0;
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mi(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.min(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mif(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mi_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
      bt = System.currentTimeMillis();
      ctr = 0;
      for (long j = 0; j < NBCALLS; j++) {
        pt.mif_f(j);
        ctr += j;
      }
      et = System.currentTimeMillis();
      tp = et - bt;
      tpa[l++] += tp;
      total += (ctr > 0 ? 1 : -1);
      
    }
    System.out.print("results for private: ");
    for (int m = 0; m < 5; m++) {
      System.out.print(tpa[m] + "\t");
    }
    System.out.println();
  }

  /* public */

  public void mu(long aI) {
    aI++;
  }
    
  public void mun(long aI) {
    long i = aI;
    i++;
  }
  
  public final void muf(long aI) {
    aI++;
  }
  
  public void mu_f(final long aI) {
    long i = aI;
    i++;
  }
  
  public final void muf_f(final long aI) {
    long i = aI;
    i++;
  }

  /* protected */
  
  protected void mo(long aI) {
    aI++;
  }
  
  protected void mon(long aI) {
    long i = aI;
    i++;
  }
  
  protected final void mof(long aI) {
    aI++;
  }
    
  protected void mo_f(final long aI) {
    long i = aI;
    i++;
  }

  protected final void mof_f(final long aI) {
    long i = aI;
    i++;
  }

  /* package */

  void mp(long aI) {
    aI++;
  }
    
  void mpn(long aI) {
    long i = aI;
    i++;
  }
    
  final void mpf(long aI) {
    aI++;
  }

  void mp_f(final long aI) {
    long i = aI;
    i++;
  }
  
  final void mpf_f(final long aI) {
    long i = aI;
    i++;
  }

  /* private */

  private void mi(long aI) {
    aI++;
  }
    
  private void min(long aI) {
    long i = aI;
    i++;
  }
    
  private final void mif(long aI) {
    aI++;
  }
    
  private void mi_f(final long aI) {
    long i = aI;
    i++;
  }
    
  private final void mif_f(final long aI) {
    long i = aI;
    i++;
  }
  
}

**Comment by revusky** [comment]
> A small test shows that one cannot rely only on assuming things or looking at byte code. The JIT compiler can do many things on the byte code.

Marc, the argument, you're making (such as it is) favors my position on this, NOT yours. If, indeed, it is a fool's errand to second-guess the Java runtime and JIT compiler (and yes, I tend to think that is generally the case!) that implies that one should simply write code in the simplest, most straightforward and readable way possible, and let the JIT do its work.

And that has the unfortunate implication that your patch was not well motivated. Therefore, yes, I reverted it.

**Comment by MarcMazas** [comment]
<that one should simply write code in the simplest, most straightforward and readable way possible, and let the JIT do its work/>
Well: I'm ready to propose more optimizations, with more impacts, real impacts, but the counterpart will be that the code will be less concise. Most of the time this covers object allocations / reuse, string handling, string concatenation, local vars referring to class fields or method parameters, final keywords. _Small streams make great rivers_.
So: ARE YOU READY TO ACCEPT THOSE, OR WILL YOU ARGUE ON EACH, KEEPING SAYING THAT YOU PREFER SLOWER CODE TO FASTER CODE BECAUSE YOU FAVOR YOUR MAINTAINABILITY TO END-USER PERFORMANCE?

**Comment by revusky** [comment]
> So: ARE YOU READY TO ACCEPT THOSE, OR WILL YOU ARGUE ON EACH, KEEPING SAYING THAT YOU PREFER SLOWER CODE TO FASTER CODE BECAUSE YOU FAVOR YOUR MAINTAINABILITY TO END-USER PERFORMANCE?

Well, first of all, you pose the above question and I'll answer it. But I posed another question and you don't answer! 

*Are you doing this with the objective of actually learning the code?*

Or is it just based on fairly jejune formalisms? Now, you are, of course, right to say that:

        if (set.contains(x)) set.add(x);

is redundant. One should just write: 

        set.add(x);

However, it is mildly annoying that you talk to me as if (a) I don't know such things and ((I do, but sometimes one has momentary lapses) and (b) as if it really makes any discernible difference!

Of course, the above is both faster (very very slightly) and also less verbose. So, yes, of course. But it's not very important really. It's the kind of thing that I would come across and think: "Gee, that's strange." I'd fix it and it would be in the next commit and I wouldn't even make a comment about it in the commit log because it's not even worth talking about. (At least in my universe...) Now, as for cases where the more verbose code is really significantly faster strike me as being quite rare. Not non-existent, but really just not worth concerning oneself with. Almost never, anyway, because these things are just not going to make a perceptible difference. I can basically promise you that.

But here is one thing to consider: having all these nitpicking issues in the issue tracker messes up the signal/noise ratio something awful. Somebody who just wants to scroll through the issues of the last few months, say, and see what's been going on, they just end up having to run through all this nothing-burger-ish stuff to find things that are meaningful. Can't you see that?

Of course, it doesn't matter in a nothingburger project, because this is the only activity they have! Just nth order bullshit like this! But when something is under meaningful development....

But anyway, the answer to your question is that I'm not very interested in changes that have extremely minor nth order speed improvements, if it is at the expense of readability. (I also tend to think that code that is more succinct tends to be more readable. There are probably exceptions, but I mean in general...) There is no practical gain, it occupies my time to respond to such things, and it reduces the signal to noise ratio pretty badly because it's just stuff that's insignificant.

So that's my answer. So, now, are you going to answer my question? 

*Is your goal here to nitpick about formalisms or are you really trying to learn the code?* 

If the answer is the latter, that you really are trying to learn the code, there is the natural follow-up question: "Why suddenly now?"

**Comment by MarcMazas** [comment]
My long term goal is to contribute (=help, =improve) JavaCC21 (as well as JavaCC).
A first step is to get rid of annoying project structure weaknesses, build problems, warnings, ...

A main area is performance (like the SQLparser problem). I do not want to contribute to something that at the end will be less performant than JavaCC.
So I need to understand how you coded it, how close or far it is from my (hope best) practices.
As warnings are a good starting point for problems, I look at them... If I find something weak, strange..., I propose a change, no need to wait, even if it is not a big silver bullet. Again, _small streams make great rivers_.
For this I have to test you first on small changes to see your reactions, as I don't want to loose time for things you will not accept.
So for the moment the result is not very positive...

Then I shall profile the code, to see where it consumes and can be improved. My experience is that there are quick wins.
Then I'll make my mind of the performance achievability.
Then I'll discuss the improvement possibilities with you.

Then if I see the things go on an acceptable direction for me, I may think of including the JavaCC21 syntax in the Eclipse plug-in.

**Comment by revusky** [comment]
This whole situation is puzzling to me. I have to ask this question: 

The work that I've done on JavaCC, this cleanup of the code that I've carried out... in your opinion, are you capable of doing that work? Or is it (as I honestly suspect) a level of work completely beyond your abilities?

But, you know, Marc, for some reason, I keep thinking about that iconic scene from 2001 Space Odyssey -- I mean, specifically, the one where the apes are contemplating the monolith. https://www.youtube.com/watch?v=lE94q60fw2Y

Strange, isn't it? That must be my subconscious trying to tell me something...

Another question that intrigues me is this: *what is the use-case for the legacy JavaCC project?*

You seem to think that these are two things that can legitimately co-exist. Yet, as far as I can see, the legacy JavaCC is just totally obsolete. Why would anybody opt to use that if they knew that JavaCC21 exists? I can't see any more case for it than using JDK 1.4 or something like that.

**Comment by MarcMazas** [comment]
>  The work that I've done on JavaCC, this cleanup of the code that I've carried out... in your opinion, are you capable of doing that work? Or is it (as I honestly suspect) a level of work completely beyond your abilities?

I have not looked at all what you did, I have not taken time to understand the JavaCC generated code, nor the JavaCC code itself for its engine part. Same for JavaCC21. But this does not change anything and does not matter for anybody, including you. Why this question?
In fact, yes, I think I am capable of this. I did this kind of work on other products.
But if somebody does some improvements, I tend to build new things on them. 

>  what is the use-case for the legacy JavaCC project?

A lot of real life / real projects have been successfully built on JavaCC. Big grammars. Tools / translators running on big applications. And yes, with its "bugs".
I already told you what are my would-be-nice-to-have-features (improve productivity in developping big grammars, improve software reuse). By the way, you complain very few people discuss on your discusion forum. You do not seem to have understood why.
And also told you that some of your features-you're-proud-of do not interest me much (like inject or nested syntactic lookahead) or not at all (like new short syntaxes).
Two things you did interest me: a) having pushed the 64k barrier, b) rewrite the generated code, for faster performance.
For a), I plan to do the same on JavaCC.
For b), it looks you did not succeed in being better than JavaCC.
So for the moment the use-case is still JavaCC, not JavaCC21.

**Comment by revusky** [comment]
> My long term goal is to contribute (=help, =improve) JavaCC21 (as well as JavaCC).

Well, I feel I should make this absolutely clear to you, and to anybody else who happens on this discussion. There is no option of being involved in both JavaCC21 and the legacy JavaCC. You'd have to choose one or the other.

Now, to be clear about this, of course, in general principle, people can do what they want, and in general principle, whatever other projects you are involved with besides this one is even none of my business. For example, I would not care particularly if somebody with a general interest in the parsing space wanted to be involved in this project and also in ANTLR.

That would be my general position, but this is a rather special situation. You see, JavaCC21 and  the legacy project are not two separate projects in the same sense that JavaCC and ANTLR are two separate projects. JavaCC21 is simply a more advanced version of JavaCC. It is the result of a massive cleanup/refactoring of the legacy JavaCC codebase. To want to be involved in both things just makes no real sense.

But there's really another issue, which is like an elephant in the room. Aside from the technical differences between JavaCC21 and the legacy tool, there is another key difference between the two:

*One of them is genuine, serious project, and the other is a __FRAUD__.*

This is very clear. All one has to do is scroll through [their commit record](https://github.com/javacc/javacc/commits/master) to see this. Granted, 1,249 commits might seem like something significant, but any closer examination shows that it is almost entirely fluff. I have made a point of going through all this, dating back to mid-2003, when the thing was open-sourced and I came to the conclusion that all of this "activity" maybe constitutes a body of a work that a single motivated person of my caliber would do in a few weeks. (Actually, I'm sure that even that is a very generous estimate.) Regardless, that they went from version 2.x and now, 18 years later, are on an 8.x cycle seems very hard to characterize as anything other than a FRAUD. It is also quite clear that there has not been a meaningful new feature in the legacy JavaCC tool for over 2 decades.

Now, that somebody who is just happening into this space does not realize that something is a fraud, that could be understandable. But that is not your case. You have been involved in JavaCC, at least peripherally, being on the various mailing lists and so on, at least since 2009. So you cannot be unaware that the legacy project is a fraud. Thus, by your desire to get involved in something *in the full knowledge that it is a __FRAUD__* you unfortunately self-identify as a fraud yourself.

This project is very undermanned and I cannot afford the luxury of wasting any time with low quality people. So you are about to be banned, as you already are, in fact, from the [Discourse forum](https://parsers.org). (I can't believe that you forgot that you have been banned there for at least half a year.) 

You are about to be banned, but I guess there is some window of time to respond to what I'm saying and maybe even get in the last word.

*The legacy JavaCC project isd

**Comment by revusky** [comment]
> > The work that I've done on JavaCC, this cleanup of the code that I've carried out... in your opinion, are you capable of doing that work? Or is it (as I honestly suspect) a level of work completely beyond your abilities?
> 
> I have not looked at all what you did, I have not taken time to understand the JavaCC generated code, nor the JavaCC code itself for its engine part. Same for JavaCC21. But this does not change anything and does not matter for anybody, including you. Why this question?

Well, why did the chicken cross the road? Presumably, to get the other side. I posed this question because I was curious about how you would answer it. Do you have another way for me to satisfy my curiosity without posing the question?

> In fact, yes, I think I am capable of this. I did this kind of work on other products.

Hold on. Didn't you just say that you had never looked at this? How would you know whether you are capable of the work or not? If somebody asked me whether I am capable of dancing the moonwalk and I never had even looked at the moonwalk, I could only answer that I don't know. Of course, once I saw a video of Michael Jackson doing the moonwalk, I would then answer quite honestly that I am not able to do that. It's strange... in the scene from 2001 Space Odyssey that I alluded to, I infer that it is clear that the apes that are contemplating the monolith know perfectly well that they are not themselves capable of creating such a thing. Or I assume that. But regardless, they are contemplating the monolith. You, when one asks whether you consider yourself capable of creating something, answer that you think you can, but have never actually looked at the thing. It is rather sad, but it seems like you are definitely on a lower level than the apes in question. 

Though, admittedly, that is not really a very important point. After all, I would not be eager to have any of those apes involved in this project either.

https://www.youtube.com/watch?v=lE94q60fw2Y

> But if somebody does some improvements, I tend to build new things on them.
> 
> > what is the use-case for the legacy JavaCC project?
> 
> A lot of real life / real projects have been successfully built on JavaCC. Big grammars. Tools / translators running on big applications. And yes, with its "bugs".

You're missing the point. Nobody ever said that no quality software was built using the legacy JavaCC tool. For example, I am the main author of FreeMarker -- certainly the core of it that includes the parser -- and that was built using the old JavaCC. It was also mostly built on top of JDK 1.4 (if I recall correctly.) The fact that FreeMarker, like countless other things, was built on top of JDK 1.4 *does not suggest that there is any __current__ use-case for building on top of JDK 1.4.*

This is just a first order fallacy. In fact, the oldest JDK version that Oracle currently supports is JDK 8. (I just looked it up.) That they do not support the older JDK's does not mean that Oracle is saying that no good software was built on top of them! That would be ludicrous! It does, however, mean that they consider those things to be obsolete at this point in time and that people should upgrade to something more current.

> I already told you what are my would-be-nice-to-have-features (improve productivity in developping big grammars, improve software reuse). By the way, you complain very few people discuss on your discusion forum. You do not seem to have understood why.

Well, *you* don't participate there currently because you've been banned for the last half year. As for why other people don't participate... well... I don't know for sure, but I have no reason to think that you know any better than I.


> And also told you that some of your features-you're-proud-of do not interest me much (like inject or nested syntactic lookahead) or not at all (like new short syntaxes).

I don't recall you ever saying that to me. I am still, at my age, blessed with a reasonably good memory, so I remember coming across some conversation you were involved in on the JavaCC mailing list. This message in particular:

https://markmail.org/message/dlkfzrmnv4ohommp

The last paragraph of the above message reads:

>Speaking of freecc, its "injection" feature is a nice feature (and different
from "action") : I would not be surprised if this could be of great help for
other languages.

You seemed to recognize that INJECT was actually quite a useful feature and were (at least implicitly) suggesting to the people in the legacy project that they should implement something similar. (*Good luck with that!*)

Now, you are talking to me like that work I did was of no value. Well, somebody has the right to change their mind, I suppose, but the other possibility is that you're just being dishonest now. In any case, if you thought that  implementing something like INJECT was something you could do, well, that was a decade ago. Why didn't you do it?

Also, if, 10 years ago, you thought that FreeCC already offered some valuable improvements over the legacy JavaCC, and INJECT was one of them, it is horrendously inconsistent to now be telling me that JavaCC21 does not offer any significant improvement, when it is, in turn, a vastly improved version of FreeCC!

I don't know what generous interpretation of your behavior in this is available, but I'm not that inclined to be generous towards you. You really seem to be some sort of chronic liar. And I really can't abide that. But even aside from that, you just continually demonstrate this appalling ignorance, like referring to nested syntactic lookahead as some "feature" I implemented. It's not a new feature really. It's a bug fix! If you write:

       LOOKAHEAD(Foo())

and Foo contains another lookahead, of course, it should do that lookahead. They always tacitly admitted that this was a bug because there was always nested semantic lookahead! Why would syntactic lookahead not nest, when semantic lookahead does? It makes no sense. It was just a bug. And I fixed it.

> Two things you did interest me: a) having pushed the 64k barrier,  b) rewrite the generated code, for faster performance.

To be clear, I never rewrote the generated code "for faster performance". I rewrote it for *clarity*. If it's a bit faster in one spot or a bit slower is not much of a concern of mine. Broadly speaking, the parsers generated by one tool or the other are not going to differ in speed all that much, because it's the same top-down recursive algorithm at the end of the day.

Besides that, performance is not really a problem with JavaCC, either JavaCC21 or the legacy tool. The parsers and tokenizers it generates tend to be pretty blindingly fast.

> For a), I plan to do the same on JavaCC.

Well, fine. But, as I said, there is no option of being involved in that project and this one. So you've chosen that one, that means. That's clear enough. Well, good luck with that. (You're gonna need it! LOL!)

> For b), it looks you did not succeed in being better than JavaCC.

Well, that's inaccurate, because I never set as a goal to make JavaCC21 discernibly faster than the legacy tool. My only goal was to fix all the outstanding issues and get the code beaten into shape to be able to develop new features... and to develop new features of course... *without giving up much in the way of performance*. And that has certainly been achieved.

> So for the moment the use-case is still JavaCC, not JavaCC21.

Well, in the above you mention at least one feature that JavaCC21 has that you want, support for supplementary characters, no? Or did you mean fixing the "Code too large problem". Regardless, you're talking out of both sides of your mouth. YOu're saying you fully intend to implement the same features I implemented in JavaCC21 in the legacy code and then you say out of the other side of your mouth that the thing to use is JavaCC. 

I banned you from the discussion forum half a year ago because I knew full well that dealing with somebody like you was just going to be a time sink. At times since, I had my doubts, thinking that I reacted to strongly, but now I see that my decision was quite correct, and I should not second-guess myself so much.

**Pull request merged**
