### PR TITLE
Java formatter goodness.

### PR DESCRIPTION
**Pull request by nickl-**
After enough "hinting" that someone should work on the `JavaFormatter` here it is now.

Implemented all operators and delimiters with appropriate spacing before and after as per sun code standards. 
Fixed type argument formatting with special attention to ? commas and spacing before LT and after GT. 
Fixed multi block statements try/catch/finally if/else-if/else formatting without new lines. 
Fixed newline bug introduced at statement visit affecting semicolon and others. 
Corrected formatting for minus operator to include -1 and 2 - 1 formatting. 
Removes rogue semicolons resulting in empty statement nodes. 
Fixed trailing spaces originating from single line comments.
Fixed bug in dead code eliminator throwing away imports for interface extends list.

Outstanding:
-  modifier order
-  squashing star imports
-  ordering import statements

I am unable to squash the space before the comma in the interface declaration extends list:
Screenshot_20230124_161741

Where that space is coming from still alludes me...

Ran it through `ant full-test` to build new bootstrap jar and ran it twice proving that all works with new jar. (bootstrap tests passed)

Ran the project through the 3rd party checkstyle again #248  with a 100000 odd error reduction.

### CODE REVIEW

**Comment by revusky** [comment]
Okay, great! I don't know to what extent I was "hinting anything. I mean, basically, this is a low-risk (or zero-risk) thing to work on because it essentially cannot really be broken! Since every Java file that the thing generates passes through this thing, if it didn't work in the sense of outputting actually incorrect code, it would be impossible to rebuild/retest anything at all. But, of course, it can be glitchy in the sense of emitting weird code in terms of whitespace. Or, actually, it could swallow (or repeat) a comment and one wouldn't know it without eyeballing the generated code. But, you know, it can't really generate anything invalid or incorrect on a real functional level.

And I guess what I meant was that this sort of thing does provide a very safe entry point in terms of gaining familiarity with the overall system. So, that's great. Thanks!

**Comment by nickl-** [comment]
> And I guess what I meant was that this sort of thing does provide a very safe entry point in terms of gaining familiarity with the overall system. So, that's great. Thanks!

Was indeed a good learning exorcise and finally getting my hands dirty with AST. Just kidding about the "hinting" and batting of eyelashes =) Needed to get done and I was all set up to bash it out.

@revusky Any idea about that space before the comma on the interface extends list?

**Comment by revusky** [comment]
> @revusky Any idea about that space before the comma on the interface extends list?`

Yes, but it took me a while to figure it out! It's really a rather tricky issue. In this specific case, the `nextCachedToken()` [here](https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/JavaFormatter.java#L112) does not return COMMA. It returns LBRACE because the following part `, java.io.Serializable` was *injected* into the AST. But `nextCachedToken` is giving you the next token based on the state of the world *before* the code injections. See [here](https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/FilesGenerator.java#L260-L266). 

You see the issue? The map of token locations that is being used for `nextCachedTokens` is not actually updated after a code injection (and, in principle this could be addressed but is probably not worth the bother) so in this case, it is actually giving an incorrect answer when you ask it what the next token is. I suppose the absolutely correct solution would be to use the AST, which is correct, but it's a bit of a hassle. You need something like:

        Node parent = op.getParent();
        if (parent instanceof TypeArguments && parent.getParent().getParent() instanceof ExtendsList) {
              Node nextSibling = parent.getParent().nextSibling();
              if (nextSibling != null && nextSibling.getTokenType() == COMMA) break;
        }
     
I suppose that would work because the parent/child/sibling relationships in the AST actually do reflect the state of things after the code injection. I started on that path, but then figured it wasn't worth the bother for what is basically a nitpicking cosmetic issue anyway. SO... finally I just did the patch that you can see. It doesn't append the space if the next cached token is LBRACE. And that works fine since we always prepend a space in front of LBRACE, so it gets the space in front in the case where it is after TypeArguments anyway. (And even if it didn't, really... who cares...)

**Comment by nickl-** [comment]
> SO... finally I just did the patch that you can see. 

Confirmed works as expected.

Had a suspicion that inject had something to do with it, which may be on track but still very far from pin pointing cache as the problem.

> and, in principle this could be addressed but is probably not worth the bother

For the most part I tend to agree, the benefits from caching certainly outweighs this gotcha, at least for this use case. However the convenience of the `getNext` family of methods on `Token` is evident when compared to the alternative going directly to the tree. Something which is sorely missed on `Node` when they are unavailable, so I can understand the impediment having to do without. Due to this utility the likelihood that others will run into this is high and because the cause is so obfuscated this will lead to frustrations. That aside, lets say it does get documented and communicated in resolution, what will be the suggested work around?...use the AST or avoid `INJECT` all together?

I tried using `previousSibling` and/or `nextSibling` on `Node`  for the task but they are less reliable then the `Token` methods (or intended for a different purpose). Was intrigued by the possibility exposed through `firstChildOfType` with the added `Predicate`, powerful stuff, but in the end I still lacked the necessary to make a viable comparison to find next or previous. I had to abandon my attempts to reproduce the pattern used for `Token` and had to find an alternative solution.

The usual approach for dealing with these issues are a blanket invalidation of the cache, which always seems like such a waste as it only ever affects a small minority causing everything to suffer Ideally a surgical cure is preferable, only resetting the effected at the point of injection. Probably left to the injector to manage, or making the injectee aware through some "injectable" contract might be more future proof. 

Either way, well done and kudos for fixing it, ta!

**Comment by revusky** [comment]
Well, I guess the thing to understand here is that there are really two things here:
- AST navigation (`getParent`, `getChild`, `nextSibling` etc) 
- Token chaining (`token.getNext`, etc.)

So, for example, in the general case, you can build a parser that doesn't do any automatic tree-building (`TREE_BUILDING_ENABLED=false`;) In that case, you would still have the token chaining, i.e. `token.getNext()` etc. In fact, you could not build any parser at all, just a lexer, and you'd still have the token chaining. So, properly understood, these are actually two API's that result from two different levels of machinery. 

The problem here is that the code injection used internally in JavaCC 21 is not doing any readjustment of the token chaining. So that is why when it generates (on the first pass)

        public interface Node implements Comparable<Node> {

but then the code injection machinery inserts another super-interface, so *post-injection* we have:

       public interface Node implements Comparable<Node> , java.io.Serializable {

The `, java.io.Serializable` is *injected* into the AST but there is no corresponding adjustment to the token chaining, which is why when it hits the closing `>` at the end of `<Node>` the token chaining machinery thinks that the next token is the right brace at the end of the line! And that's where the glitch emerges from. It adds a space based on the next token being `{` rather than what it really is, the `,`.

So this is actually a bug (a glitch at least) in the system, because the code injection was implemented without taking into account that the token chaining would basically be broken in these spots. And I guess this was always the case, because the way token chaining worked before, the very crude way with a publicly visible `next` field, I don't think that the code injection (originally implemented back in 2008!) ever adjusted these things. So it doubtless had the same glitch. A funny thing is that if you look at the [older implementation of JavaFormatter](https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/OlderJavaFormatter.java#L58) you can see there that it uses this method `code.getAllTokens()` which walks the tree recursively and gets all the tokens that way. I'm pretty sure (vaguely recall) that at some point, I tried to write it with the token chaining API's, but then discovered that it didn't work, because of this very same issue, i.e. it was skipping over the tokens that were *injected*. Since then, I decided to rewrite the JavaFormatter as a `Node.Visitor` which I figured would be more elegant and provide finer control. And also I [totally refactored the token chaining](https://javacc.com/2021/12/05/tokens-then-and-now/) but the basic problem remains: if you *inject* nodes into the AST, the token chaining will be broken at certain key points -- at least if you don't deal with the problem!

But again, they're really two different API's corresponding to two different "machines" -- syntactic as opposed to lexical -- so if you tweak the AST, adding/removing nodes, the token chaining will be wrong at those spots where things were added/removed. 

It occurs to me that it might be a good idea to put in a method that repairs the token chaining after adding/removing a Node.

> I tried using previousSibling and/or nextSibling on Node for the task but they are less reliable then the Token methods

Well, yeah, if what you really want to know is just what the next token is, then this tree-walking stuff is definitely much trickier to use, but the problem being that, with code injection, the next/previous token in the token-level API potentially gives you the wrong answer as to what the next or previous token really is! (For the most part, it only gives the wrong answer at the boundary points where code was `INJECT`ed.)

It so happens that this is not much of a show-stopper for this particular usage because it just manifests itself as  whitespace-related glitches that don't really matter. But, in the general case... 

Actually this issue comes up in implementing the Python parser, because that involves basically *injecting* "synthetic" tokens into the token stream (and tree) but that is actually handled correctly for that case! See [here](https://github.com/javacc21/javacc21/blob/master/examples/python/PythonLexer.javacc#L144) and [here](https://github.com/javacc21/javacc21/blob/master/examples/python/PythonLexer.javacc#L177). So, if you look at that, you'll see that you can chain through the tokens with getNext()/getPrevious() etc and it really should work correctly. 

So, that's really the straight story. It is a glitch, but it's a glitch in internal usage within the tool itself, because the code injection is not (currently) exposed as an API outside the tool. It is possible to fix the chaining. That's what the `prependedToken`/`AppendedToken` fields are about. So, if you want to look into that, well, okay, by all means!

Actually, it occurs to me after writing all the above, that it might be useful to have a separate getNextToken API that gives the next (or previous) token based on tree traversal, as opposed to the lexical machinery caching -- though, again, except at certain key boundary points, the two would give you the same next/previous...

**Pull request merged**
